// <auto-generated />
using GuideTI_Variacao_do_Ativo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuideTI_Variacao_do_Ativo.Migrations
{
    [DbContext(typeof(VariacaoDoAtivoContext))]
    [Migration("20230309073816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("GuideTI_Variacao_do_Ativo.Models.Variacao", b =>
                {
                    b.Property<int>("Dia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VariacaoRelacaoPrimeiraData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaricaoRelacaoD1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Dia");

                    b.ToTable("Variacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
